pipeline {
    agent {
        kubernetes {
            yaml '''
                apiVersion: v1
                kind: Pod
                spec:
                  containers:
                  - name: maven
                    image: maven:3.8.4-openjdk-17
                    command:
                    - cat
                    tty: true
            '''
        }
    }

    stages {
        stage('Cleanup Workspace') {
            steps {
                cleanWs()
                sh "echo 'Cleaned Up Workspace For Project'"
            }
        }

        stage('Code Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Test') {
            steps('Unit Testing') {
                sh "echo 'Running Unit Tests for PR'"
            }

            steps('Code Analysis') {
                sh "echo 'Running Code Analysis for PR'"
            }
        }

        stage('Develop Branch Tasks') {
            when {
                anyOf {
                    branch 'develop'
                    changeRequest target: 'develop'
                }
            }
            stages {
                stage('Build for Develop') {
                    steps {
                        sh "echo 'Building for Develop (PR or Commit)'"
                    }
                }
                stage('Deploy to Dev Environment') {
                    when {
                        allOf {
                            branch 'develop'
                            not {
                                changeRequest()
                            }
                        }
                    }
                    steps {
                        sh "echo 'Deploying to Dev Environment (Commit only)'"
                    }
                }
            }
        }

        stage('Main Branch Tasks') {
            when {
                anyOf {
                    branch 'main'
                    changeRequest target: 'main'
                }
            }
            stages {
                stage('Build for Production') {
                    steps {
                        sh "echo 'Building for Production'"
                    }
                }
                stage('Deploy to Pre-prod') {
                    when {
                        allOf {
                            branch 'main'
                            not {
                                changeRequest()
                            }
                        }
                    }
                    steps {
                        sh "echo 'Deploying to Pre-prod Environment'"
                    }
                }
            }
        }
    }

    post {
        always {
            sh "echo 'Pipeline Completed'"
        }
    }
}